baseURL: 
defaultContentLanguage: en

assetDir: static

markup:
  goldmark:
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    permalinks:


