baseURL: baseURL = "https://cj-sfsm.github.io"
theme: hugobricks
defaultContentLanguage: en
assetDir: static

disableKinds:
  - taxonomy
  - term

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false


